#!/usr/bin/python
#Author:Sign4l
#Gmail:sign4lsec@gmail.com
#instagram:sign4l_it
import os
import random
import string
class style:
    red = '\033[91m'
    green = '\033[92m'
    bold = '\033[1m'
    white = '\033[0m'
    yellow = '\033[93m'
    blue = '\033[94m'
    purple = '\033[95m'
    cyan = '\033[96m'
    gray = '\033[2m'
    Bred = '\033[101m'
clear = os.system('clear')
print (style.red+'        =============================================')
print (style.yellow+'        =============================================')
print (style.green+'        =============================================')
print (style.cyan+'        =============================================')
print (style.blue+'        =============================================')
print (style.purple+'        =============================================')
print (style.white+'                        PASSWORD MAKER')
print ('                        Author:SIGN4L')
print (style.red+'        =============================================')
print (style.yellow+'        =============================================')
print (style.green+'        =============================================')
print (style.cyan+'        =============================================')
print (style.blue+'        =============================================')
print (style.purple+'        =============================================')
print ('')

fname = raw_input(style.red+'[+]'+style.white+'Enter First Name: ')
lname = raw_input(style.red+'[+]'+style.white+'Enter Last Name: ')
number = raw_input(style.red+'[+]'+style.white+'Enter Number Phone: ')
pet = raw_input(style.red+'[+]'+style.white+'Enter Pet Name: ')
friend = raw_input(style.red+'[+]'+style.white+'Enter Friend Name: ')
year = raw_input(style.red+'[+]'+style.white+'Enter The Year Of Birth: ')
city = raw_input(style.red+'[+]'+style.white+'Enter City: ')
country = raw_input(style.red+'[+]'+style.white+'Enter Country: ')
extra = raw_input(style.red+'[+]'+style.white+'Extra Items: ')
list1 = [fname,lname,number,pet,friend,year,city,country,extra]
a = random.choice(list1)
b = random.choice(list1)
c = random.choice(list1)
d = random.choice(list1)
e = random.choice(list1)
f2 = random.choice(list1)
g = random.choice(list1)
h = random.choice(list1)
i = random.choice(list1)
def main():
    f = open('passlist.txt','w+')

    f.write(a+a+'\n')
    f.write(a+b+'\n')
    f.write(a+c+'\n')
    f.write(a+d+'\n')
    f.write(a+e+'\n')
    f.write(a+f2+'\n')
    f.write(a+g+'\n')
    f.write(a+h+'\n')
    f.write(a+i+'\n')
    f.write(b+b+'\n')
    f.write(b+c+'\n')
    f.write(b+d+'\n')
    f.write(b+e+'\n')
    f.write(b+f2+'\n')
    f.write(b+g+'\n')
    f.write(b+h+'\n')
    f.write(b+i+'\n')
    f.write(d+d+'\n')
    f.write(d+e+'\n')
    f.write(d+f2+'\n')
    f.write(d+g+'\n')
    f.write(d+h+'\n')
    f.write(d+i+'\n')
    f.write(e+e+'\n')
    f.write(e+f2+'\n')
    f.write(e+g+'\n')
    f.write(e+h+'\n')
    f.write(e+i+'\n')
    f.write(f2+f2+'\n')
    f.write(f2+g+'\n')
    f.write(f2+h+'\n')
    f.write(f2+i+'\n')
    f.write(g+g+'\n')
    f.write(g+h+'\n')
    f.write(g+h+'\n')
    f.write(g+i+'\n')
    f.write(h+h+'\n')
    f.write(h+i+'\n')
    f.write(i+i+'\n')
    f.write(i+a+'\n')
    f.write(i+b+'\n')
    f.write(i+c+'\n')
    f.write(i+d+'\n')
    f.write(i+e+'\n')
    f.write(i+f2+'\n')
    f.write(i+g+'\n')
    f.write(i+h+'\n')
    f.write(h+a+'\n')
    f.write(h+b+'\n')
    f.write(h+c+'\n')
    f.write(h+d+'\n')
    f.write(h+e+'\n')
    f.write(h+f2+'\n')
    f.write(h+g+'\n')
    f.write(g+a+'\n')
    f.write(g+b+'\n')
    f.write(g+c+'\n')
    f.write(g+d+'\n')
    f.write(g+e+'\n')
    f.write(g+f2+'\n')
    f.write(f2+a+'\n')
    f.write(f2+b+'\n')
    f.write(f2+c+'\n')
    f.write(f2+d+'\n')
    f.write(f2+e+'\n')
    f.write(e+a+'\n')
    f.write(e+b+'\n')
    f.write(e+c+'\n')
    f.write(e+d+'\n')
    f.write(d+a+'\n')
    f.write(d+b+'\n')
    f.write(b+a+'\n')
    f.write(a+b+c+'\n')
    f.write(b+a+c+'\n')
    f.write(a+a+a+'\n')
    f.write(b+b+b+'\n')
    f.write(c+c+c+'\n')
    f.write(d+d+d+'\n')
    f.write(e+e+e+'\n')
    f.write(f2+f2+f2+'\n')
    f.write(g+g+g+'\n')
    f.write(h+h+h+'\n')
    f.write(i+i+i+'\n')
    f.write(a+i+c+'\n')
    f.write(b+h+g+'\n')
    f.write(e+f2+a+'\n')
    f.write(a+c+c+'\n')
    f.write(a+h+h+'\n')
    f.write(a+f2+f2+'\n')
    f.write(i+d+d+'\n')
    f.write(d+f2+a+'\n')
    f.write(d+a+d+'\n')
    f.write(a+'pass'+'\n')
    f.write(a+'1234'+'\n')
    f.write(a+b+'1234'+'\n')
    f.write(b+'1234'+'\n')
    f.write(a+b+c+a+'\n')
    f.write(a+c+a+c+'\n')
    f.close()
if __name__ == "__main__":
    main()
